__title__ = 'swiftype_app_search'
__description__ = 'An API client for Swiftype App Search'
__url__ = 'https://github.com/swiftype/swiftype-app-search-python'
__version__ = '0.1.4'
__author__ = 'Swiftype'
__author_email__ = 'eng@swiftype.com'
