__title__ = 'elastic-app-search'
__description__ = 'An API client for Elastic App Search'
__url__ = 'https://github.com/elastic/app-search-python'
__version__ = '7.9.0'
__author__ = 'Elastic'
__author_email__ = 'support@elastic.co'
